### ISSUE TITLE
Associating Triples to its corresponding source sentences

### ISSUE THREAD

**Issue by Dhanasekar-S** [philipperemy/Stanford-OpenIE-Python#11]
The code generates triples for all the sentences in the input file. What if I want to find the triples generated out of sentence number 1 or sentence 'n' from the input file?

Is there a way to do that?

Thanks

**Comment by abjoker** [comment]
Run the single sentence instead, smh

**Comment by philipperemy** [comment]
Yes re-run it on just the first sentence or the last one independently.

Feel free to improve the tool :)
