### ISSUE TITLE
can model use in chinese information extraction?thanks.

### ISSUE THREAD

**Issue by huyanggithub** [philipperemy/Stanford-OpenIE-Python#12]
hello everyone
    now i want to use this model to solve chinese problems, I konw this model base on ollie, and ollie can not use in chinses problem, so   who can tell me if this model can use in chinese problem or how to change it in chinese ,thank you very much.

**Comment by philipperemy** [comment]
@huyanggithub hum not sure.

You can have more info here: https://nlp.stanford.edu/software/openie.html

**Comment by philipperemy** [comment]
Feel free to comment if it worked for you!
