### ISSUE TITLE
Could not find or load main class stanfordnlp_resources.stanford-corenlp -full-2018-10-05.LIBRARY-LICENSES

### ISSUE THREAD

**Issue by zachlanger19** [philipperemy/Stanford-OpenIE-Python#21]
Issue: Python script times out after downloading stanfordnlp_resources and trying to run server.

```
% java -Xmx8G -cp /Users/zachlanger/stanfordnlp_resources/stanford
-corenlp-full-2018-10-05/* edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 60
000 -threads 5 -maxCharLength 100000 -quiet True -serverProperties corenlp_server-9c0518c7aab74af
d.props -preload openie
Error: Could not find or load main class .Users.USERNAME.stanfordnlp_resources.stanford-corenlp
-full-2018-10-05.LIBRARY-LICENSES
```

System information:
MacOS Catalina 10.15
Python 3.6

```
% java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

```
% pip3 show stanford-openie
Name: stanford-openie
Version: 1.0.1
Summary: Minimalist wrapper around Stanford OpenIE
Home-page: UNKNOWN
Author: Philippe Remy
Author-email: None
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: stanfordnlp, wget
Required-by: 
```

Fix Attempts:
Tried installing stanford-corenlp-4.0.0 separately but it doesn't get used.

**Comment by philipperemy** [comment]
Clear the cache and try again.
```
rm -rf ~/stanfordnlp_resources/
```

**Comment by philipperemy** [comment]
I've restarted a build: https://github.com/philipperemy/Stanford-OpenIE-Python/pull/22/checks?check_run_id=737350184

**Comment by zachlanger19** [comment]
Cleared my cache and removed stanfordnlp_resources and it worked. Thank you for the assistance and quick response! For future reference this was on a Macbook pro 2015

**Comment by philipperemy** [comment]
@zachlanger19 great happy it worked!

**Comment by jjdiaz24** [comment]
Hello! im running it in a Colab and won't work. it keeps sending me this error message: PermanentlyFailedException: Timed out waiting for service to come alive. Do you what could be going wrong ?

**Comment by philipperemy** [comment]
@jjdiaz24 not sure you can run it with Colab. There's a java server behind the scenes that might need some ports to be open to run successfully.
