### ISSUE TITLE
Python Wrapper Error 

### ISSUE THREAD

**Issue by carolinamatuk** [philipperemy/Stanford-OpenIE-Python#23]
Hello, I have installed the python wrapper but I keep getting an error when I run your sample code. 
From these lines:
from openie import StanfordOpenIE

with StanfordOpenIE() as client:

I get 
Syntax Error: Unexpected EOF while parsing.

My question is, where is the syntax error? Or why is it saying this?

Thanks.

**Comment by carolinamatuk** [comment]
Sidenote: I am using Windows and was able to successfully install openie

**Comment by philipperemy** [comment]
@carolinamatuk hum I've never tried it on Windows. Do you have access to a Linux or Mac laptop? But maybe it does not work well with Windows..

**Comment by carolinamatuk** [comment]
Yes I do, I will try it on Linux.

**Comment by philipperemy** [comment]
@carolinamatuk yes please try it and if it works let me know. Also if you have a windows machine, you can try to make it work and open a pull request. That would be highly appreciated for our windows users (if you have time). Thanks!
