### ISSUE TITLE
Does this library not support Chinese？

### ISSUE THREAD

**Issue by klforeverl** [philipperemy/Stanford-OpenIE-Python#28]
just english?

**Comment by philipperemy** [comment]
@klforeverl no idea. It supports the scope of https://stanfordnlp.github.io/CoreNLP/.
But in the case of OpenIE, I'm not sure.

**Comment by philipperemy** [comment]
To answer your question, it's only for english for openIE.

https://stanfordnlp.github.io/CoreNLP/human-languages.html

![image](https://user-images.githubusercontent.com/4516927/90085956-2f5f7d80-dd54-11ea-99c5-0bbe48028e64.png)
