### ISSUE TITLE
Java Assertion Error

### ISSUE THREAD

**Issue by Rajat700** [philipperemy/Stanford-OpenIE-Python#3]
I am using Stanford open ie for relation extraction for a text file which contains 5000 sentences. But I am getting the following error. The text file is not empty. When I reduce the number of sentences by some amount say 2000 then it works. 
Can anyone tell me whats the problem

Traceback (most recent call last):
  File "main.py", line 165, in <module>
    if __name__ == '__main__':
  File "main.py", line 154, in main
    debug_print('filename = {}'.format(filename), verbose)
  File "main.py", line 123, in stanford_ie
    assert not java_process.returncode, 'ERROR: Call to stanford_ie exited with a non-zero code status.'
AssertionError: ERROR: Call to stanford_ie exited with a non-zero code status.

**Comment by philipperemy** [comment]
Hum not sure @Rajat700 

I have no idea what would cause this problem.

Do you have Java 1.8 installed?

```
java -version
```

Also can you try the examples in the repository and tell me if they work?

Thanks

**Comment by ronikobrosly** [comment]
I can replicate @Rajat700 's error. When I feed in a very large text file I get that same error. When I halve the size of the text file, I don't get the error. 

The examples in the repo worked for me, and I have Java 1.8.0_91 installed.

**Comment by philipperemy** [comment]
@ronikobrosly thanks. It seems that the Java implementation provided by Stanford NLP has its limitations. I don't have a solution for that except that we should maybe:
- instead of running the wrapper, execute the command line and see the Java error.
- update the binaries (they may have released a new version since then).
- split into smaller files is the easiest workaround

**Comment by ronikobrosly** [comment]
Sounds like a plan!

**Comment by philipperemy** [comment]
I could successfully run it with 5000 sentences of `Barack Obama was born in Hawaii.`. Maybe it was too simple

**Comment by philipperemy** [comment]
Ok for 100,000 it failed :)

**Comment by philipperemy** [comment]
I added a bash script to split the large corpus file into smaller file, process each one and merge the results: https://github.com/philipperemy/Stanford-OpenIE-Python/commit/52c7eabd26d3d36ca935b2a7cb7b5032ec6acbb2
