### ISSUE TITLE
Parameters on java server

### ISSUE THREAD

**Issue by reobroqn** [philipperemy/Stanford-OpenIE-Python#32]
Hello! I'm using your code, it's great! I did a little searching and found this 
![image](https://user-images.githubusercontent.com/52645376/94095582-4497f380-fe4c-11ea-97eb-f3f3b0f433f3.png)
https://stanfordnlp.github.io/CoreNLP/openie.html
Can I somehow modify to use those params in python? Is there anyway to do it? Would appreciate if you know and show me.

**Comment by philipperemy** [comment]
@reobroqn thanks! I think you can input some parameters here: https://github.com/philipperemy/Stanford-OpenIE-Python/blob/5fb65d38e1043c320218c368c5b4e271e76bbb0c/openie/openie.py#L35

**Comment by reobroqn** [comment]
![image](https://user-images.githubusercontent.com/52645376/94118401-b5083a00-fe77-11ea-8e6b-3eccea1793c0.png)
And one more thing. I encountered this problem every time I finished running code. Although my code had completed but it's pretty weird, nothing bad happened while running but a bug just show up at the end.

**Comment by philipperemy** [comment]
That's interesting. It seems like it's an error of the StanfordNLP client. You should open an issue there: https://github.com/stanfordnlp/python-stanford-corenlp.

**Comment by reobroqn** [comment]
Wait! Could you please make an example using one of those params? I'm dying groping. T_T
self.client = CoreNLPClient(annotators=['openie'], memory='8G') 
Oh and if I modify in this, it means I have to install from source, right?

**Comment by enaserianhanzaei** [comment]
@philipperemy I have the same question, imaging I want to disable 'splitter.nomodel', how should I do that? I followed your instructions by passing a dictionary as properties {'splitter.nomodel':False}, however, it doesn't seem to work


Thanks,

**Comment by reobroqn** [comment]
@enaserianhanzaei This is how I add properties. It works for me.
![Screenshot from 2021-06-03 08-44-31](https://user-images.githubusercontent.com/52645376/120573659-24431e80-c448-11eb-9ea2-e0a026d33ede.png)
I think you also have to modify it as above, then install using setup.py. 
Or you can install with dev mode (python setup.py develop) and freely edit code.

**Comment by philipperemy** [comment]
Thanks! Would be nice to have a small PR to give those parameters as arguments!
