### ISSUE TITLE
Porting to German

### ISSUE THREAD

**Issue by ChrisChross** [philipperemy/Stanford-OpenIE-Python#33]
Hi guys,

is there a way to port this nice library to german? 
Thanks in advance. 

chris

**Comment by philipperemy** [comment]
@ChrisChross not that I know of. Link:

https://stanfordnlp.github.io/CoreNLP/human-languages.html

This library is a wrapper around the OpenIE functionality of CoreNLP:

![image](https://user-images.githubusercontent.com/4516927/100035559-db2f6380-2e41-11eb-8f55-c4ac45f7db53.png)

And from this table, only english is supported for OpenIE..

**Comment by ChrisChross** [comment]
Thanks for thies neat table. Also had similar question on stanza that resolved the issue.

**Comment by philipperemy** [comment]
@ChrisChross welcome!
