### ISSUE TITLE
Unable to execute  Stanford-OpenIE-Python main.py

### ISSUE THREAD

**Issue by amitkamthane** [philipperemy/Stanford-OpenIE-Python#4]
Following Error please 
Namespace(filename='samples.txt', generate_graph=False, verbose=False)
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    exit(main(argv))
  File "main.py", line 142, in main
    entities_relations = stanford_ie(filename, verbose, generate_graphviz)
  File "main.py", line 118, in stanford_ie
    assert not java_process.returncode, 'ERROR: Call to stanford_ie exited with a non-zero code status.'
AssertionError: ERROR: Call to stanford_ie exited with a non-zero code status.

**Comment by philipperemy** [comment]
I need more information please.

Could you run the examples provided in the README?

**Comment by amitkamthane** [comment]
I was trying on windows. But let me know if it works on it.

**Comment by philipperemy** [comment]
NOTE: Windows is not currently supported! Works on UNIX systems like Linux and Mac OS.

**Comment by sybilOO** [comment]
hi , sir , my system is  Mac OS,  faced the same issue.

File "main.py", line 152, in <module>
    exit(main(argv))
  File "main.py", line 146, in main
    entities_relations = stanford_ie(filename, verbose, generate_graphviz)
  File "main.py", line 122, in stanford_ie
    assert not java_process.returncode, 'ERROR: Call to stanford_ie exited with a non-zero code status.'

**Comment by philipperemy** [comment]
@sybilOO not sure why here. Run with -v and copy/paste and identify the command that you execute at this line:

> debug_print('Executing command = {}'.format(command), verbose)

Then copy paste this command in a terminal and see which it fails.

**Comment by freshiefrey** [comment]
> hi , sir , my system is Mac OS, faced the same issue.
> 
> File "main.py", line 152, in
> exit(main(argv))
> File "main.py", line 146, in main
> entities_relations = stanford_ie(filename, verbose, generate_graphviz)
> File "main.py", line 122, in stanford_ie
> assert not java_process.returncode, 'ERROR: Call to stanford_ie exited with a non-zero code status.'

I use MacOS too, and installing GraphWiz via homebrew solved my issue. 
`brew install graphviz`
http://www.graphviz.org/download/

**Comment by zhanwenchen** [comment]
On Ubuntu, you need to first install graphviz via `sudo apt install graphviz`.
