### ISSUE TITLE
Python Compatibility

### ISSUE THREAD

**Issue by dimaelzein** [philipperemy/stanford-openie-python#41]
Can someone advise please which Python versions are compatible? I am currently using Python 3.7.1 and I am unable to install it. 
PS: I cannot upgrade the Python version, I need it for Hugging Face neuralcoref. Has anyone tried neuralcoref with stanford openie?

**Comment by philipperemy** [comment]
@dimaelzein hey I think it should work with python 3.7.1 as long as you can install some deps.
I think the tricky part here is the installation of the CoreNLP library which relies on Java.
So you need to have Java installed.
