### ISSUE TITLE
probability_cap

### ISSUE THREAD

**Issue by enaserianhanzaei** [philipperemy/stanford-openie-python#44]
Thanks for the very useful library,

My question is, how to change the affinity probability to get more confident clauses and consequently triples?

Seemingly, I should be able to change this probability by openie.affinity_probability_cap, however, when I even set that to 1, the results are still the same.

Thanks,
Elahe

**Comment by philipperemy** [comment]
On the way: https://github.com/philipperemy/stanford-openie-python/pull/45

**Comment by philipperemy** [comment]
Released in 1.1.0.
