### ISSUE TITLE
How can I filter these triples?

### ISSUE THREAD

**Issue by Gyyyym** [philipperemy/stanford-openie-python#55]
How can I filter these triples? Thank you.

**Comment by philipperemy** [comment]
Try this: https://philipperemy.github.io/information-extract/

**Comment by qinglongheu** [comment]
> Try this: https://philipperemy.github.io/information-extract/

thank you for your amazing work！can you provide a tutorial python notebook for this idea?

**Comment by philipperemy** [comment]
But this might interest you: https://github.com/philipperemy/information-extraction-with-dominating-rules
