### ISSUE TITLE
Is there a way to use coref+openie using the standford-corenlp-4.1.0 version?

### ISSUE THREAD

**Issue by Archirekh-Majumder** [philipperemy/stanford-openie-python#56]
I am trying to get triplets with coreference resolved, tried this way **triples = client.annotate(corpus, properties={ "annotators":"tokenize,ssplit,pos,lemma,depparse,ner,coref,mention,natlog,openie", "outputFormat": "json", "openie.format": "ollie", "openie.resolve_coref": "true", })** but it is giving the following error.

stanfordnlp.server.client.AnnotationException: java.lang.IllegalArgumentException: annotator "openie" requires annotation "CorefChainAnnotation". The usual requirements for this annotator are: tokenize,ssplit,pos,lemma,depparse,natlog

**Comment by philipperemy** [comment]
@Archirekh-Majumder you should probably ask this question directly on https://github.com/stanfordnlp/CoreNLP.
