### ISSUE TITLE
Error while making Graph

### ISSUE THREAD

**Issue by ayushgupt** [philipperemy/Stanford-OpenIE-Python#6]
For just a file containing one sentence, code runs file if the generate_graph flag is set to false but adding '-g' while running gives the error below.
`Namespace(filename='samples.txt', generate_graph=True, verbose=False)
/bin/sh: 1: dot: not found
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    exit(main(argv))
  File "main.py", line 142, in main
    entities_relations = stanford_ie(filename, verbose, generate_graphviz)
  File "main.py", line 126, in stanford_ie
    generate_graphviz_graph(results, verbose)
  File "main.py", line 91, in generate_graphviz_graph
    assert not dot_process.returncode, 'ERROR: Call to dot exited with a non-zero code status.'
AssertionError: ERROR: Call to dot exited with a non-zero code status.
`

**Comment by philipperemy** [comment]
Do you have the `dot` command installed?
