### ISSUE TITLE
PermanentlyFailedException: Timed out waiting for service to come alive.

### ISSUE THREAD

**Issue by ByUnal** [philipperemy/stanford-openie-python#60]
Hi there,

I'm trying this repo in my local Jupyter Notebook. My OS is Ubuntu. I'm getting the following error. Can you help me on this one ?

![image](https://github.com/philipperemy/stanford-openie-python/assets/43930582/31f39c86-14f9-49d5-83f1-50b92021746b)

end of the error:
![image](https://github.com/philipperemy/stanford-openie-python/assets/43930582/b7bd1fd3-5cf9-4f7a-b7c2-aedeeac578cb)

**Comment by philipperemy** [comment]
@ByUnal does it work if you just run the same thing with python and not jupyter?

**Comment by ByUnal** [comment]
@philipperemy Yes mate :/

![image](https://github.com/philipperemy/stanford-openie-python/assets/43930582/aee705f5-0af5-4887-a9f6-07e6986c4557)

**Comment by philipperemy** [comment]
that's weird. do you have java installed?

**Comment by ByUnal** [comment]
I was thinking that the java has already installed, but it wasn't actually :/. It works now. Thanks.

**Comment by philipperemy** [comment]
README updated.
