### ISSUE TITLE
install_dir_path logic has a mistake in it

### ISSUE THREAD

**Issue by tdene** [philipperemy/stanford-openie-python#62]
If install_dir_path is provided via environment variable, it remains a string:
https://github.com/philipperemy/stanford-openie-python/blob/master/openie/openie.py#L23

If install_dir_path is provided via argument, it becomes a Path:
https://github.com/philipperemy/stanford-openie-python/blob/master/openie/openie.py#L25

This leads to an error on the next line if install_dir_path is provided via environment variable:
https://github.com/philipperemy/stanford-openie-python/blob/master/openie/openie.py#L26

**Comment by philipperemy** [comment]
Good catch will release a quick fix.

**Comment by philipperemy** [comment]
https://github.com/philipperemy/stanford-openie-python/pull/63

**Comment by philipperemy** [comment]
Done, you can upgrade the lib. I released 1.3.2.

```
pip install stanford_openie --upgrade
```
