### ISSUE TITLE
Update on OpenIE 5

### ISSUE THREAD

**Issue by amandalmia14** [philipperemy/Stanford-OpenIE-Python#7]
Hi,

Can you please update on [OpenIE 5 ](https://github.com/dair-iitd/OpenIE-standalone)

Thanks.

**Comment by philipperemy** [comment]
@amandalmia14 this implementation is for https://nlp.stanford.edu/software/openie.html.

I'm not sure how feasible it is to port it to OpenIE 5.

Also the JARs are a bit old now. Maybe we can update them to the latest version.

I'm running a bit busy now. So if anyone could actually work on it that'd be great :)
