### ISSUE TITLE
Output also original sentence

### ISSUE THREAD

**Issue by MichalGabonay** [philipperemy/Stanford-OpenIE-Python#8]
It is possible to output also the original sentence?
For example:

Sentence 1.
RE 1
RE2

Sentence 2.
RE1
RE2

Barack Obama was born in Hawaii.
Barack Obama | was | born
Barack Obama | was born in | Hawaii

**Comment by philipperemy** [comment]
@MichalGabonay can't you just keep the mapping yourself when you call the library?

**Comment by philipperemy** [comment]
I'll close this for now.
